name: Go Build and Test

on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ] # Or your default branch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Check go formatting
      shell: bash # Explicitly use bash
      run: |
        test -z "$(gofmt -l .)" || (echo "Go files are not formatted. Please run 'go fmt ./...'"; exit 1)

    - name: Run go vet
      run: go vet ./...

    - name: Build
      run: go build -v ./cmd/photocp/...

    - name: Test
      env:
        CGO_ENABLED: "1"
      run: go test -v ./...
